name: time-tracker-backend
services:
  frontend:
    container_name: frontend
    profiles:
      - prod
    restart: always
    depends_on:
      - backend
    image: 'time-tracker-frontend-container'
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}

  backend:
    profiles:
      - prod
    container_name: backend
    restart: always
    depends_on:
      - db
    image: 'time-tracker-backend-container'
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    environment:
      - FLASK_APP=src/main.py
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - SECRET_KEY=${SECRET_KEY}
      - BACKEND_PORT=${BACKEND_PORT}
    command: 'chmod +x ./backend/entrypoint.sh'
    entrypoint: ./entrypoint.sh

  proxy:
    profiles:
      - prod
    image: nginx:alpine
    container_name: proxy
    restart: always
    depends_on:
      - backend
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - '${BACKEND_PORT}:80'

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_CONTAINER_PORT}"
    depends_on:
      - db
