name: time-tracker-backend
services:
  frontend:
    container_name: frontend
    restart: always
    depends_on:
      - backend
    image: 'time-tracker-frontend-container'
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}

  backend:
    container_name: backend
    restart: always
    depends_on:
      - db
    image: 'time-tracker-backend-container'
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - FLASK_APP=src/main.py
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - SECRET_KEY=${SECRET_KEY}
      - BACKEND_PORT=${BACKEND_PORT}
    entrypoint: ./entrypoint.sh

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_CONTAINER_PORT}"
    depends_on:
      - db
