"""empty message

Revision ID: 5e97a84660f4
Revises: 216f86b6427f
Create Date: 2022-10-19 19:25:40.365221

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5e97a84660f4'
down_revision = '216f86b6427f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_project_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'])
    op.drop_column('task', 'project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('project', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_project_fkey', 'task', 'project', ['project'], ['id'])
    op.drop_column('task', 'project_id')
    # ### end Alembic commands ###
